### PR TITLE
Features and Fixes Part 2

### LINKED ISSUE #363: Date Tag Property

### LINKED ISSUE #365: Disc Tag Property
Add `Disc` & `Disc Total` as an additional properties.

### LINKED ISSUE #375: Remember Format String
---

`%artist%- %title%`
 %artist%- %title%

`Artist1- Song1`
Artist1- Song1.mp3

---

`%artist% - %title%`
 %artist%- %title%

`Artist1 - Song1`
Artist1 - Song1.mp3

---

Tagger Help, Format Strings

---

I guess it's a typo? But then again it's quite widespread if it's indeed a typo, because not only `%artist%- %title%` but also the other suggestions such as `%title%- %artist%` & `%track%- ℅title℅`. I'm on Fedora Silverblue, latest version of Tagger (flatpak) btw.

### PR DESCRIPTION
**Pull request by nlogozzo**
Closes #363 
Closes #365 
Closes #375 

Blocking:
- [x] https://github.com/Zeugma440/atldotnet/issues/235

### CODE REVIEW

**Comment by nlogozzo** [comment]
@kissthermite
You can download and install the `.flatpak` file from the assets section on this CI build: https://github.com/NickvisionApps/Tagger/actions/runs/6601503583 to test the remembering of format strings and the sorting files by album with disc number while we wait for our backend's (atldotnet) developer to fix the flac file issue.

Just a note, the format string used for file name to tag will be remembered independently of that used by tag to file name. 

Once you download and extract the `.flatpak` file from the assets, you can use these commands to install it:
```
#from the directory containing the .flatpak file
flatpak install org.nickvision.tagger-x64.flatpak
flatpak run org.nickvision.tagger//master
```

Once you've tested and are done with it (or you can keep using it until the next beta release) you can uninstall it with:
```
flatpak uninstall org.nickvision.tagger//master
```

**Comment by kissthermite** [comment]
> Feel free to comment with any issues, comments, questions, or concerns :))

name

It does remember my custom format string even after closing Tagger. Such a nice QOL. Good job @nlogozzo!

**Comment by kissthermite** [comment]
> Feel free to comment with any issues, comments, questions, or concerns :))

name

name

And album sorting now behave the way i expected too. Another job well done!

**Comment by nlogozzo** [comment]
@kissthermite Glad everything works as expected :)

This build should contain the fix for `PublishingDate` and flac files: https://github.com/NickvisionApps/Tagger/actions/runs/6603980868

Once you confirm that works I will merge this PR and release RC1 and we should be all good for a stable release on Friday!

**Comment by kissthermite** [comment]
> @kissthermite Glad everything works as expected :)
> 
> This build should contain the fix for `PublishingDate` and flac files: https://github.com/NickvisionApps/Tagger/actions/runs/6603980868
> 
> Once you confirm that works I will merge this PR and release RC1 and we should be all good for a stable release on Friday!

name

it's working! :rocket:

**Comment by nlogozzo** [comment]
Yay!! I have to go to work now but once I get home later td I'll merge and do a release :)

**Comment by kissthermite** [comment]
> Yay!! I have to go to work now but once I get home later td I'll merge and do a release :)

I just edited my comment in case you didn't see it.

>I just realized that there's currently no way to remove Publishing Date tag?

name

That trash can button can be seen on `Custom Properties`
`VORBIS-VENDOR` would do nicely beside `Pick a date/Date` button

**Comment by nlogozzo** [comment]
> That trash can button can be seen on Custom Properties
VORBIS-VENDOR would do nicely beside Pick a date/Date button

Ah, good idea! Will implement that when I get home instead

**Comment by nlogozzo** [comment]
> > That trash can button can be seen on Custom Properties
> > VORBIS-VENDOR would do nicely beside Pick a date/Date button
> 
> Ah, good idea! Will implement that when I get home instead

@kissthermite Ok, done! Use this build to test: https://github.com/NickvisionApps/Tagger/actions/runs/6605232433

**Review by fsobolev — CHANGES_REQUESTED** [review]
I think we should take disc number to consideration everywhere where we compare track numbers: for sorting by artist, year and genre too.

**Comment by nlogozzo** [comment]
> I think we should take disc number to consideration everywhere where we compare track numbers: for sorting by artist, year and genre too.

Done in latest commit!

**Comment by kissthermite** [comment]
name

name

---

@nlogozzo  another job completed fantastically!

**Review by fsobolev — APPROVED** [review]

**Comment by nlogozzo** [comment]
@kissthermite RC1 will come in a little bit. 

Just be advised that configurations are kept independent of branches. Meaning flatpak beta and flatpak master will be different. So upon installing rc1, your format string won't be remembered until you use it for the first time on the version.

**Comment by fsobolev** [comment]
> Just be advised that configurations are kept independent of branches. Meaning flatpak beta and flatpak master will be different. So upon installing rc1, your format string won't be remembered until you use it for the first time on the version.

Why is that? Flatpak data dir is always `~/.var/app/org.nickvision.tagger` no matter the branch

**Comment by nlogozzo** [comment]
> > Just be advised that configurations are kept independent of branches. Meaning flatpak beta and flatpak master will be different. So upon installing rc1, your format string won't be remembered until you use it for the first time on the version.
> 
> Why is that? Flatpak data dir is always `~/.var/app/org.nickvision.tagger` no matter the branch

I could be wrong. I thought the whole branch was kept separate from each other. Guess it's just the binaries and the rest is shared.

**Pull request merged**
