### PR TITLE
Lyrics Improvements

### LINKED ISSUE #225: Lyrics Support
Hi, first of all thanks for the awesome app and the fact that you're actively maintaining it !

Second is, I don't know much about audio tags, I think I learned a few things while trying to understand what was wrong.

So here's the story :
I'm using Oto Music on Android to listen to my `.flac` songs, and also to fetch the synced lyrics. I thought the lyrics would be shown afterwards on Tagger, but it's not the case.
I tried to understand where the lyrics were stored, and apparently they're stored in a `lyrics` custom tag. I saw that you did an update 2 weeks ago to add support for custom tags, and indeed they're here.
Still, the lyrics tag doesn't show up. I found out while using Ex Falso (another tag editor) that apparently the issue _could_ be that the lyrics are (obviously) stored in some sort of "multi-line" field, because on Ex Falso there's a checkbox to "unsee multi-lines tags", which makes the "lyrics" tag disappear.
It may not be the issue, but if this is indeed the issue, is there any way to add support for "Multi-Lines" custom tags ?

### PR DESCRIPTION
**Pull request by nlogozzo**
Closes #225 

- [x] Update atldotnet to V5.0.0 which fixes unable to read syncrhonized tags in LRC format
- [x] Make it so custom properties with valid property names can't be created (i.e can't create custom properties who's name are `lyrics`, `title`, `artist`, etc...)
- [x] Add offset field to synchronized lyrics
- [x] Sort new sync lyrics by timstamp 
- [x] No two of the same timestamp
- [x] Import and export sync lyrics to and from LRC
- [x] (Unrelated to Lyrics) Don't allow musicbrainz/acoustid webservice if fingerprint error

image

### CODE REVIEW

**Comment by nlogozzo** [comment]
Actually, going to add the offset field for synchronized lyrics...

**Comment by SpicyWasab** [comment]
(hi, still me :P)
Looks really cool !
Why only the offset field though ? I mean, to be honest I don't think the other fields are _really_ useful as for 90% of them they're basically the same as the ones included in the files's metadatas, but since we're able to edit one of the fields, maybe you could allow all of them to be edited ? Not necessarily hardcoding every single field (since sometimes apps seems to use non-official fields, like the "tool" field in 2 of the songs I sent you), but just allowing the ones already there to be edited as well as letting the user add some others would be awesome. Like custom tags.
I have only two possible implementations in mind :
- When clicking on the "Add" button, one could choose between "Add a property" or "Add a lyrics line". If the user chooses property, the user will face 2 text-entries, the first one being the name of the lyrics. There could be some suggestions or a dropdown that includes the standardized properties in order to help the user, the same type of suggestions as the "Genre" field. The other text-entry would be for the value.
- 2 buttons, one to add a property and one to add a lyrics line. The "add a proprety" would be the same as described above. I think this implementation could be better since it removes one step for the user to achieve it's goal.
(like, with the first one it would be "clicking on the button > choosing between property or lyrics > adding the adding", and the second one would be "clicking on the button > adding the value".) Guess the second one follows GNOME's HIG better as well (the rule of "minimize the required steps to do something")

And ... it's another overcomplicated wall of text, but the "TLDR" would just be "maybe let the user add whatever field they want, as well as editing the ones already there in the lyrics data. It would bring more flexibility to this feature.".

Btw sorry if I'm being annoying, I'm just suggesting some improvements to help making this awesome app better and better c:

**Comment by nlogozzo** [comment]
> And ... it's another overcomplicated wall of text, but the "TLDR" would just be "maybe let the user add whatever field they want, as well as editing the ones already there in the lyrics data. It would bring more flexibility to this feature.".

As you said the offset field is something that's not already in the tag. It's a useful lyrics fields that can tell a music player to start showing lyrics at an offset time.

I don't know of any other lyrics fields because those of the tag.(i.e title, artist, etc...) . I mean the whole purpose of the import LRC feature it to just grab the lyrics for a file and then continue editing in Tagger if that makes sense.

> Btw sorry if I'm being annoying, I'm just suggesting some improvements to help making this awesome app better and better c:

Nonsense it's never annoying :) you said it yourself, your helping us make this app even better!

**Comment by SpicyWasab** [comment]
Yeah alright. I guess the title, artist and album fields are only useful when the lyrics are in a separate file. There's no really need to add them to the lyrics as well since they're embedded.

It would be cool though if Tagger doesn't overwrite the unused properties when editing the lyrics then. (but if it does that's no big deal, to me at least)

And yeah, fine c:

**Pull request merged**
