### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Nickvision Tagger/App](https://hosted.weblate.org/projects/nickvision-tagger/app/).

It also includes following components:

* [Nickvision Tagger/Docs](https://hosted.weblate.org/projects/nickvision-tagger/docs/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by fsobolev** [comment]
@daudix-UFO will you fix+finish translation before the next release or should I?

**Comment by daudix-UFO** [comment]
I will try to do so now, sorry for not doing so earlier

**Comment by daudix-UFO** [comment]
@fsobolev I guess it should be fine now

**Comment by fsobolev** [comment]
> I will try to do so now, sorry for not doing so earlier

No problem, I usually work on translations when RC is out, it's just that Oque on Weblate messes with our translations whenever they want and there seem to be no way to contact them so there's no way to coordinate the work 🤷🏻‍♂️ 

> I guess it should be fine now

Great, thanks

**Pull request merged**
