### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Nickvision Tagger/App](https://hosted.weblate.org/projects/nickvision-tagger/app/).

It also includes following components:

* [Nickvision Tagger/Docs](https://hosted.weblate.org/projects/nickvision-tagger/docs/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by nlogozzo — APPROVED** [review]

**Comment by CHEFSUSHIWILL1** [comment]
Thank you

**Comment by CHEFSUSHIWILL1** [comment]
https://github.com/nlogozzo Thank you

**Comment by CHEFSUSHIWILL1** [comment]
@nlogozzo

**Comment by CHEFSUSHIWILL1** [comment]
``
Duplicate of #

**Comment by CHEFSUSHIWILL1** [comment]
<details><summary>Details</summary>
<p>



</p>
</details>

**Comment by CHEFSUSHIWILL1** [comment]
https://github.com/nlogozzo

**Pull request merged**
