### PR TITLE
Fixes + Ignore in Filename To Tag

### LINKED ISSUE #248: Slow Tag saving on multiple files
Saving Tags on multiple files at once takes a very long time. For example, with an audiobook with 12 files, 266 MB total size, removing the field "total tracks" on all 12 files at once took over 2.5 minutes to save. In Ear Tag by comparison, the same action finishes near-instantly. It shouldn't take nearly that long, so there might be something wrong with the way tags are saved.

### LINKED ISSUE #251: Add ability to ignore in format string
`%%` would represent ignoring a part of the string.

For example if the filename is: `01. Artist1- Song1`
The format string could be: `%tract%. %%` to just extra `01` and ignore everything else

### LINKED ISSUE #259: doing a drag'n'drop crashes the app
Hello there, i guess the title says it all

this is the terminal output...

`UnhandledException - unhandled exception: System.InvalidCastException: Unable to cast object of type 'GObject.Object' to type 'Gio.File'.
   at NickvisionTagger.GNOME.Views.MainWindow.OnDrop(DropTarget sender, DropSignalArgs e) in /run/build/org.nickvision.tagger/NickvisionTagger.GNOME/Views/MainWindow.cs:line 563
   at GObject.ReturningSignal`3.<>c__DisplayClass11_0.<Connect>b__0(Value returnValue, Value[] parameters)
   at GObject.Closure.InternalCallback(IntPtr closure, IntPtr returnValuePtr, UInt32 nParamValues, ValueData[] paramValuesData, IntPtr invocationHint, IntPtr userData)`

by the way, thank you for developing beautiful gnome apps :)

### LINKED ISSUE #264: High CPU Usage With M4A Fingerprint Calculation
(_Okay, I admit that this title was a joke._)

Recently I noticed that my computer starts overheating for no reason. Sometimes, after a while the fan kicks in really hard and my computer gets really hot.
*When I say really it's, like, it suddenly starts to get really noisy.*

It happened again a few minutes ago, so I opened Mission Center, and I may have found the culprit :eyes:

Capture d’écran du 2023-08-17 15-34-18

I remember that I've opened Tagger briefly to edit some tracks, and closed it directly after using the shortcut `ctrl + Q` before continuing doing some things (using GNOME Builder, Edge and Workbench, along with other tiny apps like the Icon Library, Typography, etc.)
When I took the screen, only Mission Center was opened though.

~~Now that I think about, I'm really unsure if the fan issue started since I use Tagger, or only since I use the last beta version :thinking:~~
Edit : still unsure if it's related to the beta version, but when I think about some times when it got really noisy, I think it was always when I used tagger, sometimes quite a lot.

I'm gonna do some tests to see. I didn't saw any other issue about that, so maybe it's just me or under really particular conditions :thinking:.

*But if it's really Tagger, wow draining nearly 30% of the battery in about 20 minutes to edit some metadatas is really a lot lol.*
(it's not even exagerated x))

Anyways, I'm still in vacations but I'm gonna post a reply if I have some other infos or precise steps to reproduce. If you have any request feel free to ask !
(I'm using Fedora Silverblue on a Microsoft Surface **__Laptop__ Go** 2)

### PR DESCRIPTION
**Pull request by nlogozzo**
Closes #248 
Closes #251 
Closes #259
Closes #264 

Blocking ATL Issues:
- [x] https://github.com/Zeugma440/atldotnet/issues/215
- [x] https://github.com/Zeugma440/atldotnet/issues/217
- [x] https://github.com/Zeugma440/atldotnet/issues/218

### CODE REVIEW

**Comment by nlogozzo** [comment]
Everything is done in this PR...however waiting for an atldotnet fix: https://github.com/Zeugma440/atldotnet/issues/215

**Comment by fsobolev** [comment]
Maybe `xdg-music` and `xdg-download` would be enough instead of home?

**Comment by nlogozzo** [comment]
> Maybe `xdg-music` and `xdg-download` would be enough instead of home?

I really don't think so in this case because the slowness affects literally any sandboxed folder...so I think `home` permissions is best to really avoid this isue for 95% of users (those tagging files from a `USB`/`Network Share` will still experience this unfortunatly as `home` doesn't cover that)

**Comment by fsobolev** [comment]
> avoid this isue for 95% of users

I honestly doubt any of 95% users have *tagged* music files outside of music and download folders. And if I'm not mistaken these permissions will only give "Partially unsafe" unlike "Unsafe" (red) with home permission in GNOME Software (can't check myself since I'm on KDE), that's the reason why I'm for more strict permissions.
But if I'm wrong and there's no difference, then full home permission will give no harm.

**Comment by nlogozzo** [comment]
> Everything is done in this PR...however waiting for an atldotnet fix: [Zeugma440/atldotnet#215](https://github.com/Zeugma440/atldotnet/issues/215)

This was released, but there is a new issue that will cause this PR to be blocked: https://github.com/Zeugma440/atldotnet/issues/217

**Comment by nlogozzo** [comment]
>  I honestly doubt any of 95% users have _tagged_ music files outside of music and download folders. And if I'm not mistaken these permissions will only give "Partially unsafe" unlike "Unsafe" (red) with home permission in GNOME Software (can't check myself since I'm on KDE), that's the reason why I'm for more strict permissions

It will mark it as unsafe, but to me that's a small price to pay for the benefits. 

> I honestly doubt any of 95% users have tagged music files outside of music and download folders.

But if you think this is the case then we can change it...

**Comment by fsobolev** [comment]
> But if you think this is the case then we can change it...

Well, maybe it's just me, I prefer to keep everything organized, so... From my point of view, yes, music and download is enough. Unfortunately we don't have a way to tell if that's the same for most users... Time for telemetry? 😄

**Comment by nlogozzo** [comment]
> > But if you think this is the case then we can change it...
> 
> Well, maybe it's just me, I prefer to keep everything organized, so... From my point of view, yes, music and download is enough. Unfortunately we don't have a way to tell if that's the same for most users... Time for telemetry? 😄

I'm the same way...everything is in my music folder 🤣...I'll ask the issue creater where their files are and if when we release the update many ppl still complain, we'll change it to home i guess.

**Pull request merged**
